### ISSUE TITLE
Question about dynamic_prob()

### ISSUE THREAD

**Issue by P2i42** [dzld00/Adaptive-Feature-Interpolation-for-Low-Shot-Image-Generation#2]
Hi, thanks for your magnificent work! 
I am now using FastGAN + AFI to train on grumpy_cat and shell datasets, which are both less than 100 images, with batch_size=8 and dynamic_prob(). 
![image](https://user-images.githubusercontent.com/45916661/211702756-d581f5d5-ed3a-4367-9a99-838cd896c406.png)
From Fig.7 of your paper, the k and p should be increasing significantly during the training. However, I found that the k and p are still close to 1 and 0, respectively, even after 70000 iterations in my experiment.
I trained with fixed p=0.9 and k=3 on grumpy_cat dataset before, and the results seems to be good. So from my perspective, the dynamic_prob() is maybe not working se well with FastGAN or these two datasets? Could you please provide some insights?

**Comment by dzld00** [comment]
Hi, above averaged ks were recorded during training using StyleGAN2 on CIFAR-10. Plots of k and optimal param choices can be different on different datasets and network architectures

**Comment by P2i42** [comment]
Thanks for your reply!
Is it possible to share the param settings of FastGAN + AFI on some of the mentioned datasets from Table 4.? That will be very helpful! 
![image](https://user-images.githubusercontent.com/45916661/211974513-1ea880d2-980d-430d-950b-dcaf7b9846fd.png)

**Comment by dzld00** [comment]
On FastGAN with fixed large p usually results are not bad, but generally improvement is less significant than using StyleGAN2
